validator:
  name: bob
  staked: 175000000000000ugert
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 50000000ugert
genesis:
  chain_id: stella-1
  app_state:
    crisis:
      constant_fee:
        denom: ugert
        amount: "1000000"
    gov:
      voting_params:
        voting_period: "5m"
      deposit_params:
        min_deposit:
          - denom: ugert
            amount: "10000000"
    mint:
      minter:
        annual_provisions: "0.0"
        inflation: "0.0"
      params:
        blocks_per_year: "6311520"
        goal_bonded: "0.67"
        inflation_max: "0"
        inflation_min: "0"
        inflation_rate_change: "0"
        mint_denom: ugert
    staking:
      params:
        bond_denom: ugert
    denom:
      params:
        creation_fee:
          - amount: "1750000"
            denom: "ugert"
    wasm:
      params:
        code_upload_access:
          permission: "Everybody"
        instantiate_default_permission: "Everybody"
accounts:
  - name: bob
    coins:
      - 175000000000000ugert
